---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

  roles:
    - role: dominiquefuchs.loki_compose
